version: "2"
services:
    customer-service:
        image: customer-service
        container_name: customer-service
        build:
            context: ./customers-service
            dockerfile: Dockerfile
        restart: on-failure
        tty: true
        mem_limit: 1024M
        mem_reservation: 512M
        ports:
            - 6060:6060
        volumes:
            - /etc/hosts:/etc/hosts
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default

    invoiceservice:
        container_name: invoiceservice
        build:
            context: ./invoiceservice
            dockerfile: Dockerfile
        image: invoiceservice
        restart: on-failure
        tty: true
        mem_limit: 1024M
        mem_reservation: 512M
        ports:
            - 7070:7070
        volumes:
            - /etc/hosts:/etc/hosts
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default
#
#    postgres:
#        image: postgres:11
#        container_name: postgres
#        restart: on-failure
#        tty: true
#        ports:
#            - 5432:5432
#        volumes:
#        - /etc/hosts:/etc/hosts
#        - /var/run/docker.sock:/var/run/docker.sock
#        - /Users/ritgirdh/Desktop/tools/postgres:/var/lib/postgresql/data

networks:
    default: